image: gitpod/workspace-full-vnc
ports:
  - port: 5900
  - port: 35900
  - port: 6080
tasks:
  - init: python3 setup.py install
  - init: npm i -g bash-language-server
vscode:
  extensions:
    - ms-python.anaconda-extension-pack@1.0.1:zDfOOe7FoQk40SnrhxWS5g==
    - KevinRose.vsc-python-indent@1.4.0:pb+bIlsFJOAdUNBE31dQwQ==
    - mgesbert.python-path@0.0.11:JKeT9N0dYesuMTRK8HkQsw==
    - codezombiech.gitignore@0.6.0:oJP0UqwrXt2Qgt5QRm1BIQ==
    - mads-hartmann.bash-ide-vscode@1.3.3:nKzoGKv01MgvvtFdx+Dtuw==