image:
  file: .gitpod.dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
tasks:
  - init: python3 setup.py install
    prebuild: npm i -g bash-language-server
    prebuild: pytest tests/test.py
vscode:
  extensions:
    - ms-python.anaconda-extension-pack@1.0.1:zDfOOe7FoQk40SnrhxWS5g==
    - KevinRose.vsc-python-indent@1.4.0:pb+bIlsFJOAdUNBE31dQwQ==
    - mgesbert.python-path@0.0.11:JKeT9N0dYesuMTRK8HkQsw==
    - Kasik96.swift@0.1.0:Q5PBUv3yxGt0LugfEN0nsg==
    - unpublished.sourcekit-lsp@0.0.1:NJBDyUtdIfPBJcBUYsntWQ==
    - codezombiech.gitignore@0.6.0:oJP0UqwrXt2Qgt5QRm1BIQ==
    - mads-hartmann.bash-ide-vscode@1.3.3:nKzoGKv01MgvvtFdx+Dtuw==
    - ms-vscode.csharp@1.21.6:fOJc7eXM5l6unQA2ZgsGew==
