image: gitpod/workspace-full-vnc
ports:
  - port: 5900
  - port: 35900
  - port: 6080
tasks:
  - init: python3 setup.py install
vscode:
  extensions:
    - ms-python.anaconda-extension-pack@1.0.1:zDfOOe7FoQk40SnrhxWS5g==
    - KevinRose.vsc-python-indent@1.4.0:pb+bIlsFJOAdUNBE31dQwQ==
    - mgesbert.python-path@0.0.11:JKeT9N0dYesuMTRK8HkQsw==