language: python
services:
  - docker
os:
  - linux
  - osx
  - windows
jobs:
  allow_failures:
    - os: osx
    - os: windows
script:
  - docker build -f Dockerfile .
  - python3 setup.py install
  - bash setup.sh
  - javac buttonInstall.java
