language: python
services:
- docker
jobs:
  include:
  - name: "Linux build"
    python: 3.7
  - name: "Mac OSX build"
    os: osx
    osx_image: xcode11
    language: shell
  - name: "Windows build"
    os: windows
    language: shell
    before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH  allow_failures:
    allow_failures:	
      - os: osx
      - os: windows
install:
- pip3 install codecov pytest
script:
- docker build -f Dockerfile .
- docker build -f .gitpod.dockerfile .
- python3 setup.py install
- bash setup.sh
- javac buttonInstall.java
- coverage run tests/test.py
after_success:
- codecov
- coverage xml
- curl https://deepsource.io/cli | sh
- "./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml"
