language: python

services:
  - docker

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - os: osx
    - os: windows

script:
  - docker build -f Dockerfile .
  - python3 setup.py install
  - bash setup.sh
  - javac buttonInstall.java
  - coverage run test_hello.py

# Report results to DeepSource
after_success:
  # Generate coverage report in xml format
  - coverage xml

  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # Report coverage artifact to 'test-coverage' analyzer
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
