name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Nothing is going on please refile if needed'
        stale-pr-message: 'Code out of date'
        stale-issue-label: 'STALE'
        stale-pr-label: 'STALE'
